export enum APP_ROUTES {
  HOME = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  ACCOUNT_SETTINGS = "/dashboard/accountSettings",
  DIGITAL_PERSONA = "/dashboard/digitalPersona",
  PERSONALIZATION = "/personalization",
  SUBSCRIPTIONS = "/dashboard/subscriptions",
  CART = "/cart",
  DASHBOARD = "/dashboard",
  ORDERS = "/dashboard/orders",
  APPOINTMENTS = "/dashboard/appointments",
  MEASUREMENTS = "/dashboard/measurements",
  OUTFIT_RECOMMENDATIONS = "/dashboard/outfit-recommendations",
  GROOMING_RECOMMENDATIONS = "/dashboard/grooming-recommendations",
  RESET_PASSWORD = "/login/reset-password",
  VENDORS = "/vendors",
}
