export enum UI_STATUS {
  SERVICE_CART = "SERVICE_CART",
  STYLE_CLUB_NAVIGATION = "STYLE_CLUB_NAVIGATION",
  NO_SCREENS_FOUND = "NO_SCREENS_FOUND",
}

export enum API_ERRORS {
  MOBILE_NOT_VERIFIED = "MOBILE_NOT_VERIFIED",
  LOGIN_FAILED = "LOGIN_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export enum AUTH_STATE {
  LOADING = "loading",
  AUTHENTICATED = "authenticated",
  UNAUTHENTICATED = "unauthenticated",
  SESSION_TOKEN_DATA = "session-token",
}

export enum DP_FORM_IDS {
  FORM_5_ID = "608d42832831161efcb9a6f6",
  FORM_6_ID = "60c2fa761ede7a3740f41775",
}

export enum OCCASIONS {
  PRODUCTS = "products",
}

export enum MASTER_FILTERS {
  MASTER_GROOMING_CATEGORIES = "master_grooming_categories",
}

export enum ADMINS {
  MPF_ADMIN = "MPF_ADMIN",
  STYLE_CLUB = "STYLE_CLUB",
  BRAND_PARTNERS = "BRAND_PARTNERS",
  DIGITAL_IDENTITY = "DIGITAL_IDENTITY",
  VENDOR = "VENDOR",
  PRODUCTS = "PRODUCTS",
}

export enum VENDOR_STATUS_ENUM {
  CREATED = "CREATED",
  DEACTIVATED = "DEACTIVATED",
  PAUSED = "PAUSED",
  SUBSCRIBED = "SUBSCRIBED",
}
